#!/usr/bin/env python
# -*- coding:UTF-8 -*-


RSSDOC_OUTFMT_NULL = 0
RSSDOC_OUTFMT_TUPLE = 1
RSSDOC_OUTFMT_TEXT = 2
RSSDOC_OUTFMT_JSON = 3

RSSDOC_OUTDEST_NULL = 0
RSSDOC_OUTDEST_DB = 1
RSSDOC_OUTDEST_FILE = 2
